id: P008116
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W20140
  title: མགོ་ལོག་ལོ་རྒྱུས་དེབ་ཐེར།
  author: ''
  volumes:
    5c67a68da2e0426d9eed67b7beacafc7:
      image_group_id: I5764
      title: ''
      volume_number: 1
      total_pages: 308
      base_file: v001.txt
