id: P008116
initial_creation_type: ocr
source_metadata:
  id: bdr:W20140
  title: མགོ་ལོག་ལོ་རྒྱུས་དེབ་ཐེར།
  author: ''
  volumes:
    5c67a68da2e0426d9eed67b7beacafc7:
      image_group_id: I5764
      title: ''
      volume_number: 1
      total_pages: 308
ebook_metadata:
  title: མགོ་ལོག་ལོ་རྒྱུས་དེབ་ཐེར།
  author: ''
  sku: P008116
  cover: cover.jpg
  layers:
  - pagination
